CREATE TABLE Captures(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	drive_model TEXT,
	drive_sn TEXT,
	isNVMe INTEGER,
	NVMeSerialNumberDetectionFail INTEGER,
	drive_size BIGINT,
	drive_nickname TEXT,
	partition_label TEXT,
	partition_number INTEGER,
	partition_size BIGINT,
	partition_free_space BIGINT,
	volume_guid TEXT,
	capture_properties INTEGER,
	capture_datetime TEXT,
	capture_lines_number INTEGER,
	capture_files_number INTEGER,
	capture_directories_number INTEGER,
	capture LONGBLOB,
	sizes LONGBLOB,
	creation_times LONGBLOB,
	last_access_times LONGBLOB,
	last_mod_times LONGBLOB
)